### ISSUE TITLE
fix gaem

### ISSUE THREAD

**Issue by 2048khz-gachi-rmx** [rwf93/Starbound#10]
BORN TO SEGFAULT
C++ IS A FUCK
鬼神 free() Em All 1989
410,757,864,530 LINKER ERRORS

**Comment by rwf93** [comment]
How can you host Starbound on GitHub? Why would I want to code for someone who doesn't implement things for free? Yes, it would require me to install all dependencies, but in the real world? There would only be violence. If you have any kind of humanity, I implore you consider finding some other project. Then again, Chucklefish might have payed their employees a long time ago. (Referencing rwf93, Starbound, 09/17/2023)

**Comment by 2048khz-gachi-rmx** [comment]
\> 'ouse we need to finish this game
did you try the programming code?
\> oi did try the programming code
only stupid people try the programming code. you are stupid

\>> i try the stupid code
YOU ARE UNPAID
\>> this vexes me.

\> i have bugs dripping down my code that are dripping
\>> that's bad
\> i also look like piss due to my poor shaders
\>> you need shader code! also i haven't spoken in a while
no! shader code will kill the game. he needs lua to live

:O

\> i feel better, no more fps thank you doctor
i am very smart
luajit: i too am in this shitpost
![house](https://github.com/rwf93/Starbound/assets/44749188/06628ac9-db3f-448f-8e74-8672b8b56127)

**Comment by rwf93** [comment]
y'know this issue reminds me of the time i buried that coder at 46.854521095007414, -110.40641513177252 on November 17th 2021 at 11:53 PM after killing them with a .357 Smith and Wesson magnum revolver purchased from Guns N Gear Sports located in Idaho Falls on January 23th 2020 at 5:32 PM, Serial Number - BVA0200. The reason I did this was due to the fact that they added 1 gorgillion requests, saying "fix game" of course had to do the only sensible thing and proceeded to stalk them for the following 3 days after the altercation, waiting for a prime opportunity to fire exactly 6 rounds into their torso at a distance of 15 meters, or approximately 49 to 50 glm units away.

(for all intensive purposes, this is a comedic skit and not a real event)
